type Account implements Node {
  id: Binary!
  firstname: String!
  lastname: String!
  emailAddress: EmailAddress!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input SignUpInput {
  emailAddress: EmailAddress!
  firstname: String!
  lastname: String!
  password: String!
}

input AuthenticateInput {
  emailAddress: EmailAddress!
  password: String!
}
