scalar Binary
scalar EmailAddress
scalar DateTime

directive @private on OBJECT | FIELD_DEFINITION

type Authentication {
  token: String!
}

input BinaryQueryOperatorInput {
  eq: Binary
  ne: Binary
  in: [Binary!]
  nin: [Binary!]
}

input StringQueryOperatorInput {
  eq: String
  ne: String
  in: [String!]
  nin: [String!]
  startsWith: String
  contains: String
}
