interface Node {
  id: Binary!
}

union NodeResult = Account | Product

type Query {
  """
  It was modified because this was how I interpreted Query node
  """
  node(id: Binary!): NodeResult!
}
