type Product implements Node {
  id: Binary!
  name: String!
  description: String!
  owner: Account!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type ProductConnection {
  edges: [ProductEdge!]!
  pageInfo: PageInfo!
}

type PageInfo {
  hasNextPage: Boolean!
  endCursor: Binary
}

type ProductEdge {
  cursor: Binary!
  node: Product!
}

input AccountInput {
  id: Binary!
  emailAddress: String!
}

input CreateProductInput {
  name: String!
  description: String!
  owner: AccountInput!
}

input UpdateProductInput {
  id: Binary!
  body: UpdateProductBody!
}

input UpdateProductBody {
  name: String
  description: String
}

input DeleteProductInput {
  id: Binary!
}

input ProductsFilter {
  id: BinaryQueryOperatorInput
  name: StringQueryOperatorInput
}

input ProductSortInput {
  name: Int
  createdAt: Int
}
"""
Ran out of time, when using an id for updateProduct/deleteProduct, use the id createProduct mutation returns,
the id returned by the query is not formatted correctly yet.
"""
type Mutation {
  createProduct(input: CreateProductInput!): Product! @private

  updateProduct(input: UpdateProductInput!): Product! @private

  deleteProduct(input: DeleteProductInput!): Boolean! @private
}

type Query {
  products(
    first: Int = 10
    after: Binary
    filter: ProductsFilter
    sort: ProductSortInput
  ): ProductConnection!
}
